# Generated by Django 3.2.11 on 2023-05-26 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 26, 19, 6, 5, 835366, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
