# Generated by Django 3.2.11 on 2023-06-03 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20230603_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 17, 26, 9, 579400, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(choices=[('s', 'ثبت شده'), ('e', 'در انتظار تماس'), ('m', 'معلق ')], default='در انتظار تماس', max_length=1, verbose_name='وضعیت'),
        ),
    ]
