# Generated by Django 3.2.11 on 2023-06-03 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230603_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 18, 15, 30, 563802, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='servise',
            field=models.CharField(max_length=120, verbose_name='خدمت'),
        ),
    ]
