# Generated by Django 3.2.11 on 2023-06-03 21:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230603_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 21, 23, 5, 914341, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.CreateModel(
            name='WorkSampel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('title', models.CharField(blank=True, max_length=120, null=True, verbose_name='لینک')),
                ('colleague', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='colleague_workampel', to=settings.AUTH_USER_MODEL, verbose_name='هم کار')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها ',
            },
        ),
    ]
