# Generated by Django 3.2.11 on 2023-06-03 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230604_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksampel',
            name='job',
        ),
        migrations.AddField(
            model_name='worksampel',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_user_work_sampel', to='dashboard.Services', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 21, 39, 10, 528304, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
