# Generated by Django 3.2.11 on 2023-06-03 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20230604_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 21, 42, 43, 661827, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
