# Generated by Django 3.2.11 on 2023-06-03 22:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_article_published_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksampel',
            name='services',
        ),
        migrations.AddField(
            model_name='worksampel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='work_sampel', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='worksampel',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='لینک'),
        ),
        migrations.AddField(
            model_name='worksampel',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 22, 13, 46, 736913, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='worksampel',
            name='title',
            field=models.CharField(default=None, max_length=120, verbose_name='عنوان'),
        ),
    ]
