# Generated by Django 3.2.11 on 2023-06-03 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20230604_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 22, 23, 3, 806, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
