# Generated by Django 3.2.11 on 2023-06-03 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_article_published_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksampel',
            name='show_in_work_sampel_page',
        ),
        migrations.AddField(
            model_name='services',
            name='show_in_work_sampel_page',
            field=models.BooleanField(default=True, verbose_name='نمایش در صفحه نمونه کارها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 22, 23, 37, 594584, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
