# Generated by Django 3.2.11 on 2023-06-05 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20230604_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='important_taxt',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='متن مهم '),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 14, 49, 19, 649550, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
