# Generated by Django 3.2.11 on 2023-06-05 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20230605_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 14, 49, 23, 158567, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
