# Generated by Django 3.2.11 on 2023-06-05 20:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20230605_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 20, 11, 43, 58060, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
