# Generated by Django 3.2.11 on 2023-06-06 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20230605_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticle',
            name='image',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 14, 29, 16, 622460, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
