# Generated by Django 3.2.11 on 2023-06-06 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20230606_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryarticle',
            name='slug',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 14, 35, 34, 369548, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
