# Generated by Django 3.2.11 on 2023-06-06 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20230606_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 15, 15, 49, 104838, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
