# Generated by Django 3.2.11 on 2023-06-06 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20230606_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 18, 44, 34, 128522, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
