# Generated by Django 3.2.11 on 2023-06-07 15:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20230606_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, verbose_name='عنوان')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('subject', models.CharField(choices=[('t', 'درخواست اعمال تغیرات'), ('m', 'درخواست مشاوره'), ('s', 'درخواست سفارش'), ('g', 'گزارش مشکل'), ('d', 'سایر ')], max_length=3, verbose_name='موضوع تیکت')),
                ('status', models.CharField(choices=[('o', 'باز'), ('c', 'بسته ')], default='o', max_length=1, verbose_name='وضعیت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='TicketAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ')),
                ('ticket', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ticket', verbose_name='تیکت ')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': ' پاسخ تیکت ها',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 15, 51, 19, 340422, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
