# Generated by Django 3.2.11 on 2023-06-08 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20230607_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(default=None, max_length=7, verbose_name='کد تیکت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 18, 19, 58, 965375, tzinfo=utc), verbose_name='زمان انتشار'),
        ),
    ]
